// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARETfOv2VRyEzB31gGLd7dRIzwe6lGiWQ',
    appId: '1:583721058483:android:f5cefa9f108c49ff0db0c6',
    messagingSenderId: '583721058483',
    projectId: 'cartopia-a1250',
    storageBucket: 'cartopia-a1250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUwM1Sg9URGfAkHHveB0DQK9nBRAnHyZA',
    appId: '1:583721058483:ios:24263cbae2d9b1290db0c6',
    messagingSenderId: '583721058483',
    projectId: 'cartopia-a1250',
    storageBucket: 'cartopia-a1250.appspot.com',
    androidClientId: '583721058483-7eq3rf0j59ndjoa6so091k47m6nlipvv.apps.googleusercontent.com',
    iosClientId: '583721058483-al7l7b5m1u5jp2cm0i8hhrq5q1qk2jbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartopia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUwM1Sg9URGfAkHHveB0DQK9nBRAnHyZA',
    appId: '1:583721058483:ios:cfc7c760eff67aac0db0c6',
    messagingSenderId: '583721058483',
    projectId: 'cartopia-a1250',
    storageBucket: 'cartopia-a1250.appspot.com',
    androidClientId: '583721058483-7eq3rf0j59ndjoa6so091k47m6nlipvv.apps.googleusercontent.com',
    iosClientId: '583721058483-j1ko2s8n1pql3l2g364a7ct1shfj4erf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cartopia.RunnerTests',
  );
}
